### ISSUE TITLE
[NEW] - AnimixPlay

### ISSUE THREAD

**Issue by tomthebotfly** [Elryyyyyyyy/taigarr#5]
URL: https://animixplay.to/

Why should i add this ?: One of the most popular sites along with generally being highly respected due to the quality of the website.

**Comment by Elryyyyyyyy** [comment]
Due to the websites way of displaying Anime its not possible to track Episodes, im sorry, i should list sitest that dont work.

**Comment by Elryyyyyyyy** [comment]
If the site is not working, please make a new report for updating the site
