### ISSUE TITLE
New anime site requests

### ISSUE THREAD

**Issue by randoomdude** [Elryyyyyyyy/taigarr#7]
https://animedao.to/
:Has more movies and OVAs
https://animelon.com/
:For watching with Japanese subtitles

**Comment by Elryyyyyyyy** [comment]
Other sites have movies and ovas too, site looks sketchy as hell.
Animelon would be nice, but their delivery system of episodes doesnt work well with tracking.

**Comment by randoomdude** [comment]
since animixplay.to is dead now can you reconsider animedao?

**Comment by randoomdude** [comment]
what about the new animixplay.fun?
